booking/urls.py
from django.urls import path
from .views import BookingView

urlpatterns = [
    path('', BookingView.as_view(), name='booking'),
]

main/urls.py
from django.urls import path
from .views import IndexView

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
]

master/urls.py
from django.urls import path
from .views import MasterListView, MasterDetailView

urlpatterns = [
    path('', MasterListView.as_view(), name='masters'),
    path('<int:pk>', MasterDetailView.as_view(), name='master'),
]

user/urls.py
from django.urls import path
from .views import UserView, ManagerMasterListView, ManagerMasterUpdateView, ManagerMasterCreateView, \
    ManagerMasterDeleteView, ManagerServiceDeleteView, ManagerServiceListView, ManagerServiceCreateView, \
    ManagerServiceUpdateView, ManagerCalendarUpdateView, ManagerCalendarListView, ManagerCalendarCreateView, \
    ManagerCalendarDeleteView, ManagerBookingUpdateView, ManagerBookingCreateView, ManagerBookingDeleteView, \
    ManagerBookingListView, UserLoginView, UserLogoutView, UserSignupView

urlpatterns = [
    path('', UserView.as_view(), name='user'),

    path('login', UserLoginView.as_view(), name='login'),
    path('signup', UserSignupView.as_view(), name='signup'),
    path('logout', UserLogoutView.as_view(), name='logout'),

    path('manager/masters', ManagerMasterListView.as_view(), name='manager_masters'),
    path('manager/masters/<int:pk>', ManagerMasterUpdateView.as_view(), name='manager_master'),
    path('manager/masters/add', ManagerMasterCreateView.as_view(), name='manager_masters_add'),
    path('manager/masters/delete/<int:pk>', ManagerMasterDeleteView.as_view(), name='manager_masters_delete'),

    path('manager/calendars', ManagerCalendarListView.as_view(), name='manager_calendars'),
    path('manager/calendars/<int:pk>', ManagerCalendarUpdateView.as_view(), name='manager_calendar'),
    path('manager/calendars/add', ManagerCalendarCreateView.as_view(), name='manager_calendar_add'),
    path('manager/calendars/delete/<int:pk>', ManagerCalendarDeleteView.as_view(), name='manager_calendar_delete'),

    path('manager/services', ManagerServiceListView.as_view(), name='manager_services'),
    path('manager/services/<int:pk>', ManagerServiceUpdateView.as_view(), name='manager_service'),
    path('manager/services/add', ManagerServiceCreateView.as_view(), name='manager_service_add'),
    path('manager/services/delete/<int:pk>', ManagerServiceDeleteView.as_view(), name='manager_service_delete'),

    path('manager/bookings', ManagerBookingListView.as_view(), name='manager_bookings'),
    path('manager/bookings/<int:pk>', ManagerBookingUpdateView.as_view(), name='manager_booking'),
    path('manager/bookings/add', ManagerBookingCreateView.as_view(), name='manager_booking_add'),
    path('manager/bookings/delete/<int:pk>', ManagerBookingDeleteView.as_view(), name='manager_booking_delete'),
]

booking/models.py
from django.contrib.auth.models import User
from django.db import models
from master.models import Master
from service.models import Service
from django.urls import reverse


# Create your models here.
class Booking(models.Model):
    master = models.ForeignKey(Master, on_delete=models.CASCADE, verbose_name='Мастер')
    service = models.ForeignKey(Service, on_delete=models.CASCADE, verbose_name='Услуга')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Клиент')
    time_start = models.TimeField(verbose_name='Время начала')
    date = models.DateField(verbose_name='Дата')

    def __str__(self):
        return self.master

    def get_absolute_url(self):
        return reverse('manager_bookings')

    class Meta:
        db_table = 'bookings'
        verbose_name = 'Бронирование'
        verbose_name_plural = 'Бронирования'

master/models.py
from django.db import models
from service.models import Service
from django.urls import reverse


# Create your models here.
class Master(models.Model):
    RANG_CHOICES = (
        (0, 'Ранг 1'),
        (1, 'Ранг 2')
    )
    STATUS_CHOICES = (
        (0, 'Не активен'),
        (1, 'Активен')
    )
    name = models.CharField(max_length=255, verbose_name='Имя мастера')
    rang = models.IntegerField(default=0, choices=RANG_CHOICES, verbose_name='Ранг')
    phone = models.IntegerField(verbose_name='Телефон')
    service = models.ManyToManyField(Service, verbose_name='Услуги')
    description = models.TextField(null=True, verbose_name='Описание')
    status = models.IntegerField(default=0, choices=STATUS_CHOICES, verbose_name='Статус')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('manager_masters')

    class Meta:
        db_table = 'masters'
        verbose_name = 'Мастер'
        verbose_name_plural = 'Мастера'


class Calendar(models.Model):
    master = models.ForeignKey(Master, on_delete=models.CASCADE, verbose_name='Мастер')
    date = models.DateField(verbose_name='Дата')
    time_start = models.TimeField(verbose_name='Начало рабочего дня')
    time_end = models.TimeField(verbose_name='Конец рабочего дня')

    def __str__(self):
        return self.master.name

    def get_absolute_url(self):
        return reverse('manager_calendars')

    class Meta:
        db_table = 'calendars'
        verbose_name = 'График работы'
        verbose_name_plural = 'Графики работы'

service/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Service(models.Model):
    title = models.CharField(max_length=255, verbose_name='Название услуги')
    description = models.TextField(verbose_name='Описание услуги')
    time = models.IntegerField(verbose_name='Продолжительность (в мин.)')
    price = models.IntegerField(verbose_name='Стоимость услуги')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('manager_services')

    class Meta:
        db_table = 'services'
        verbose_name = 'Услуга'
        verbose_name_plural = 'Услуги'

booking/views.py
from django.views.generic import TemplateView


# Create your views here.
class BookingView(TemplateView):
    template_name = 'booking/service_list.html'
    extra_context = {
        'title': 'Бронирование',
        'subtitle': 'Lorem Ipsum'
    }

master/views.py
import datetime
from django.conf import settings
from django.shortcuts import redirect
from django.views.generic import DetailView, ListView
from .models import Master
from service.models import Service
from booking.forms import BookingServiceForm
from booking.utils import calc_period
from booking.models import Booking


# Create your views here.
class MasterListView(ListView):
    model = Master
    template_name = 'master/master_list.html'
    context_object_name = 'master_list'
    paginate_by = settings.RESULTS_PER_PAGE
    extra_context = {
        'title': 'Мастера',
        'subtitle': 'Список наших мастеров'
    }


class MasterDetailView(DetailView):
    model = Master
    template_name = 'master/master.html'
    extra_context = {
        'title': 'Мастер',
        'subtitle': 'Lorem Ipsum'
    }

    def get_form(self, service, date, free_time):
        form = BookingServiceForm(
            time_start_choices=[(time, time) for time in free_time],
            initial={
              'master': self.object.id,
              'date': date,
              'service': service.id,
              'user': self.request.user.id
            })

        return form

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        services = Service.objects.filter(master=self.object)

        if not self.request.user.is_authenticated:
            context['need_auth'] = True
            return context

        bookings = []
        for service in services:
            forms = []
            for i in range(7):
                date = datetime.date.today() + datetime.timedelta(days=i)
                free_time = calc_period(master=self.object, service=service, date=date)
                if free_time:
                    forms.append(self.get_form(service, date, free_time))

            if forms:
                bookings.append({
                    'service': service,
                    'forms': forms
                })

        context['bookings'] = bookings
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        booking = Booking(
            master=self.object,
            user=self.request.user,
            service=Service.objects.get(id=request.POST.get('service')),
            date=request.POST.get('date'),
            time_start=request.POST.get('time_start')
        )
        booking.save()
        return redirect('/masters', pk=kwargs['pk'])

service/views.py
import datetime
from django.views.generic import DetailView, ListView
from django.shortcuts import redirect
from django.conf import settings
from .models import Service
from master.models import Master
from booking.forms import BookingServiceForm
from booking.utils import calc_period
from booking.models import Booking


# Create your views here.
class ServiceListView(ListView):
    model = Service
    template_name = 'service/service_list.html'
    context_object_name = 'service_list'
    paginate_by = settings.RESULTS_PER_PAGE
    extra_context = {
        'title': 'Услуги',
        'subtitle': 'Список наших цен и услуг доступных в ближайшие 7 дней'
    }

    def get_queryset(self):
        queryset = super().get_queryset().filter(
            master__status=True,
            master__calendar__date__range=(datetime.date.today(), datetime.date.today() + datetime.timedelta(days=7))
        ).distinct()

        return queryset


class ServiceDetailView(DetailView):
    model = Service
    template_name = 'service/service.html'
    extra_context = {
        'title': 'Услуга',
        'subtitle': 'Детали услуги'
    }

    def get_form(self, master, date, free_time):
        form = BookingServiceForm(
            time_start_choices=[(time, time) for time in free_time],
            initial={
              'master': master.id,
              'date': date,
              'service': self.object.id,
              'user': self.request.user.id
            })

        return form

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        masters = Master.objects.filter(status=1, service=self.object)

        if not self.request.user.is_authenticated:
            context['need_auth'] = True
            return context

        bookings = []
        for master in masters:
            forms = []
            for i in range(7):
                date = datetime.date.today() + datetime.timedelta(days=i)
                free_time = calc_period(master, self.object, date)
                if free_time:
                    forms.append(self.get_form(master, date, free_time))

            if forms:
                bookings.append({
                    'master': master,
                    'forms': forms
                })

        context['bookings'] = bookings
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        booking = Booking(
            master=Master.objects.get(id=request.POST.get('master')),
            user=self.request.user,
            service=self.object,
            date=request.POST.get('date'),
            time_start=request.POST.get('time_start')
        )
        booking.save()
        return redirect('/services', pk=kwargs['pk'])

user/views.py
from django.urls import reverse_lazy
from django.shortcuts import redirect
from django.conf import settings
from django.views.generic import TemplateView, ListView, UpdateView, DeleteView, CreateView
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from user.mixins import UserCheckAdministratorMixin
from master.models import Master, Calendar
from master.forms import MasterForm, CalendarForm
from service.forms import ServiceForm
from service.models import Service
from booking.models import Booking
from booking.forms import BookingForm
from user.forms import SignupForm
from .forms import LoginForm


# Create your views here.
class UserView(TemplateView):
    template_name = 'user/index.html'
    extra_context = {
        'title': 'Пользователь',
        'subtitle': 'Lorem'
    }


class ManagerMasterListView(LoginRequiredMixin, UserCheckAdministratorMixin, ListView):
    model = Master
    template_name = 'user/manager/masters.html'
    context_object_name = 'master_list'
    extra_context = {
        'title': 'Мастера',
        'subtitle': 'Управление мастерами'
    }


class ManagerMasterUpdateView(LoginRequiredMixin, UserCheckAdministratorMixin, UpdateView):
    model = Master
    form_class = MasterForm
    template_name = 'user/manager/master.html'
    context_object_name = 'master'
    extra_context = {
        'title': 'Редактирование мастера',
        'subtitle': 'Внесение изменений к мастеру'
    }


class ManagerMasterCreateView(LoginRequiredMixin, UserCheckAdministratorMixin, CreateView):
    model = Master
    form_class = MasterForm
    template_name = 'user/manager/master.html'
    extra_context = {
        'title': 'Добавление мастера',
        'subtitle': 'Добавление нового мастера',
    }


class ManagerMasterDeleteView(LoginRequiredMixin, UserCheckAdministratorMixin, DeleteView):
    model = Master
    success_url = "/user/manager/masters"


class ManagerCalendarListView(LoginRequiredMixin, UserCheckAdministratorMixin, ListView):
    model = Calendar
    template_name = 'user/manager/calendars.html'
    context_object_name = 'calendar_list'
    extra_context = {
        'title': 'Графики работы',
        'subtitle': 'Управление графиками работы мастеров салона'
    }


class ManagerCalendarUpdateView(LoginRequiredMixin, UserCheckAdministratorMixin, UpdateView):
    model = Calendar
    form_class = CalendarForm
    template_name = 'user/manager/calendar.html'
    context_object_name = 'calendar'
    extra_context = {
        'title': 'Редактирование мастера',
        'subtitle': 'Внесение изменений к мастеру'
    }


class ManagerCalendarCreateView(LoginRequiredMixin, UserCheckAdministratorMixin, CreateView):
    model = Calendar
    form_class = CalendarForm
    template_name = 'user/manager/calendar.html'
    extra_context = {
        'title': 'Новый график работы',
        'subtitle': 'Добавление графика работы',
    }


class ManagerCalendarDeleteView(LoginRequiredMixin, UserCheckAdministratorMixin, DeleteView):
    model = Calendar
    success_url = "/user/manager/calendars"


class ManagerServiceListView(LoginRequiredMixin, UserCheckAdministratorMixin, ListView):
    model = Service
    template_name = 'user/manager/services.html'
    context_object_name = 'service_list'
    extra_context = {
        'title': 'Услуги',
        'subtitle': 'Управление услугами салона'
    }


class ManagerServiceUpdateView(LoginRequiredMixin, UserCheckAdministratorMixin, UpdateView):
    model = Service
    form_class = ServiceForm
    template_name = 'user/manager/service.html'
    context_object_name = 'service'
    extra_context = {
        'title': 'Редактирование услуги',
        'subtitle': 'Внесение изменений в услугу'
    }


class ManagerServiceCreateView(LoginRequiredMixin, UserCheckAdministratorMixin, CreateView):
    model = Service
    form_class = ServiceForm
    template_name = 'user/manager/service.html'
    extra_context = {
        'title': 'Новая услуга',
        'subtitle': 'Добавление новой услуги',
    }


class ManagerServiceDeleteView(LoginRequiredMixin, UserCheckAdministratorMixin, DeleteView):
    model = Service
    success_url = "/user/manager/services"


class ManagerBookingListView(LoginRequiredMixin, UserCheckAdministratorMixin, ListView):
    model = Booking
    template_name = 'user/manager/bookings.html'
    context_object_name = 'booking_list'
    extra_context = {
        'title': 'Бронирования',
        'subtitle': 'Управление бронированиями салона'
    }


class ManagerBookingUpdateView(LoginRequiredMixin, UserCheckAdministratorMixin, UpdateView):
    model = Booking
    form_class = BookingForm
    template_name = 'user/manager/booking.html'
    context_object_name = 'service'
    extra_context = {
        'title': 'Редактирование бронирования',
        'subtitle': 'Внесение изменений в бронирование'
    }


class ManagerBookingCreateView(LoginRequiredMixin, UserCheckAdministratorMixin, CreateView):
    model = Booking
    form_class = BookingForm
    template_name = 'user/manager/booking.html'
    extra_context = {
        'title': 'Новое бронирование',
        'subtitle': 'Добавления нового бронирования',
    }


class ManagerBookingDeleteView(LoginRequiredMixin, UserCheckAdministratorMixin, DeleteView):
    model = Booking
    success_url = "/user/manager/bookings"


class UserLoginView(LoginView):
    form_class = LoginForm
    template_name = 'user/login.html'
    success_url = reverse_lazy('user/manager')
    redirect_authenticated_user = True
    extra_context = {
        'title': 'Авторизация',
        'subtitle': 'Для того, чтобы использовать сервис выполните авторизацию',
    }


class UserSignupView(CreateView):
    model = User
    form_class = SignupForm
    template_name = 'user/signup.html'
    success_url = reverse_lazy('login')
    extra_context = {
        'title': 'Регистрация профиля',
        'subtitle': 'Создайте профиль для того, чтобы использовать BearsPoint',
    }

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('user')
        else:
            return super().dispatch(request, *args, **kwargs)


class UserLogoutView(LogoutView):
    next_page = settings.LOGOUT_REDIRECT_URL

templates/user/manager/booking.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="header">
        <h1>{{ title }}</h1>
        <div class="subtitle text-muted">{{ subtitle }}</div>
    </div>
    <div class="row">
        <div class="col-8">
            <div class="card">
                <div class="card-heading">
                    <h2>Редактирование бронирования</h2>
                    <div class="subtitle text-muted">Для того, чтобы отредактировать бронирование заполните форму ниже</div>
                </div>
                <form method="post">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="{{ form.master.auto_id }}" class="form-label">{{ form.master.label }}</label>
                        {{ form.master }}
                        <div class="form-text">{{ form.master.help_text }}</div>
                    </div>
                    <div class="mb-3">
                        <label for="{{ form.service.auto_id }}" class="form-label">{{ form.service.label }}</label>
                        {{ form.service }}
                        <div class="form-text">{{ form.service.help_text }}</div>
                    </div>
                    <div class="mb-3">
                        <label for="{{ form.user.auto_id }}" class="form-label">{{ form.user.label }}</label>
                        {{ form.user }}
                        <div class="form-text">{{ form.user.help_text }}</div>
                    </div>
                    <div class="row">
                        <div class="col-6">
                            <div class="mb-3">
                                <label for="{{ form.date.auto_id }}" class="form-label">{{ form.date.label }}</label>
                                {{ form.date }}
                                <div class="form-text">{{ form.date.help_text }}</div>
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="mb-3">
                                <label for="{{ form.time_start.auto_id }}" class="form-label">{{ form.time_start.label }}</label>
                                {{ form.time_start }}
                                <div class="form-text">{{ form.time_start.help_text }}</div>
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary btn-with-icon"><i class="fi fi-rr-disk"></i>Сохранить</button>
                    {{ form.errors }}
                </form>
            </div>
        </div>
        {% include 'user/menu.html' %}
    </div>
</div>
{% endblock content %}

templates/user/manager/bookings.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="header">
        <h1>{{ title }}</h1>
        <div class="subtitle text-muted">{{ subtitle }}</div>
    </div>
    <div class="row">
        <div class="col-8">
            <div class="card card-manager">
                <div class="icon"><i class="fi fi-rr-calendar"></i></div>
                <div>
                    <h3>Добавление бронирования</h3>
                    <div class="mb-3 text-muted small">Для того, чтобы добавить новое бронирование на оказание услуг, перейдите по ссылке ниже.</div>
                    <div>
                        <a href="{% url 'manager_booking_add' %}" class="btn btn-primary btn-with-icon"><i class="fi fi-rr-add"></i>Добавить бронирование</a>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-heading">
                    <h2>Бронирования</h2>
                    <div class="subtitle">Список бронирований на услуги</div>
                </div>
                <table id="table-bookings" class="display">
                    <thead>
                        <tr>
                            <th>Имя мастера</th>
                            <th>Услуга</th>
                            <th>Пользователь</th>
                            <th>Дата</th>
                            <th>Время</th>
                            <th>Действия</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for booking in booking_list %}
                    <tr>
                        <td>{{ booking.master }}</td>
                        <td>{{ booking.service }}</td>
                        <td>{{ booking.user }}</td>
                        <td>{{ booking.date }}</td>
                        <td>{{ booking.time_start }}</td>
                        <td>
                            <a href="{% url 'manager_booking' pk=booking.id %}" class="btn btn-sm btn-with-icon"><i class="fi fi-rr-eye"></i>Смотреть</a>
                            <button type="button" class="btn btn-sm btn-with-icon btn-delete-booking" data-bs-toggle="modal" data-bs-target="#delete-booking" data-url="{% url 'manager_booking_delete' pk=booking.id %}" data-title="{{ booking.master }}"><i class="fi fi-rr-trash"></i>Удалить</button>
                        </td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        {% include 'user/menu.html' %}
    </div>
</div>

<div class="modal fade" id="delete-booking" tabindex="-1" aria-labelledby="delete-booking-label" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="delete-booking-label"></h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Данная операция приведет к удалению бронирования без возможности восстановления. Подтвердите это действие.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Закрыть</button>
          <form method="post" action="">
              {% csrf_token %}
              <button type="submit" class="btn">Подтвердить</button>
          </form>
      </div>
    </div>
  </div>
</div>
{% endblock content %}
{% block scripts %}
<script>
$(".btn-delete-booking").click(function () {
    var url = $(this).attr('data-url');
    var title = $(this).attr('data-title');

    $('#delete-booking-label').text(title);
    $('form').attr('action', url);
});
$('#table-bookings').DataTable({
    searching: false,
    paging: false,
    info: false
});
</script>
{% endblock scripts %}

templates/user/manager/calendar.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="header">
        <h1>{{ title }}</h1>
        <div class="subtitle text-muted">{{ subtitle }}</div>
    </div>
    <div class="row">
        <div class="col-8">
            <div class="card">
                <div class="card-heading">
                    <h2>Редактирование графика</h2>
                    <div class="subtitle text-muted">Для того, чтобы отредактировать график работы заполните форму ниже</div>
                </div>
                <form method="post">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="{{ form.master.auto_id }}" class="form-label">{{ form.master.label }}</label>
                        {{ form.master }}
                        <div class="form-text">{{ form.master.help_text }}</div>
                    </div>
                    <div class="mb-3">
                        <label for="{{ form.date.auto_id }}" class="form-label">{{ form.date.label }}</label>
                        {{ form.date }}
                        <div class="form-text">{{ form.date.help_text }}</div>
                    </div>
                    <div class="row">
                        <div class="col-6">
                            <div class="mb-3">
                                <label for="{{ form.time_start.auto_id }}" class="form-label">{{ form.time_start.label }}</label>
                                {{ form.time_start }}
                                <div class="form-text">{{ form.time_start.help_text }}</div>
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="mb-3">
                                <label for="{{ form.time_end.auto_id }}" class="form-label">{{ form.time_end.label }}</label>
                                {{ form.time_end }}
                                <div class="form-text">{{ form.time_end.help_text }}</div>
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary btn-with-icon"><i class="fi fi-rr-disk"></i>Сохранить</button>
                    {{ form.errors }}
                </form>
            </div>
        </div>
        {% include 'user/menu.html' %}
    </div>
</div>
{% endblock content %}

templates/user/manager/masters.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="header">
        <h1>{{ title }}</h1>
        <div class="subtitle text-muted">{{ subtitle }}</div>
    </div>
    <div class="row">
        <div class="col-8">
            <div class="card card-manager">
                <div class="icon"><i class="fi fi-rr-user"></i></div>
                <div>
                    <h3>Добавление мастера</h3>
                    <div class="mb-3 text-muted small">Для того, чтобы добавить нового мастера, перейдите по ссылке ниже.</div>
                    <div>
                        <a href="{% url 'manager_masters_add' %}" class="btn btn-primary btn-with-icon"><i class="fi fi-rr-add"></i>Добавить мастера</a>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-heading">
                    <h2>Мастера</h2>
                    <div class="subtitle text-muted">Список мастеров салона</div>
                </div>
                <table id="table-masters" class="display">
                    <thead>
                        <tr>
                            <th>Имя мастера</th>
                            <th>Ранг</th>
                            <th>Телефон</th>
                            <th>Статус</th>
                            <th>Действия</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for master in master_list %}
                    <tr>
                        <td>{{ master.name }}</td>
                        <td>{{ master.get_rang_display }}</td>
                        <td>{{ master.phone }}</td>
                        <td>{{ master.get_status_display }}</td>
                        <td>
                            <a href="{% url 'manager_master' pk=master.id %}" class="btn btn-sm btn-with-icon"><i class="fi fi-rr-eye"></i>Смотреть</a>
                            <button type="button" class="btn btn-sm btn-with-icon btn-delete-master" data-bs-toggle="modal" data-bs-target="#delete-master" data-url="{% url 'manager_masters_delete' pk=master.id %}" data-title="{{ master.name }}"><i class="fi fi-rr-trash"></i>Удалить</button>
                        </td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        {% include 'user/menu.html' %}
    </div>
</div>

<div class="modal fade" id="delete-master" tabindex="-1" aria-labelledby="delete-master-label" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="delete-master-label"></h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Данная операция приведет к удалению мастера без возможности восстановления. Подтвердите это действие.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Закрыть</button>
          <form method="post" action="">
              {% csrf_token %}
              <button type="submit" class="btn">Подтвердить</button>
          </form>
      </div>
    </div>
  </div>
</div>
{% endblock content %}
{% block scripts %}
<script>
$(".btn-delete-master").click(function () {
    var url = $(this).attr('data-url');
    var title = $(this).attr('data-title');

    $('#delete-master-label').text(title);
    $('form').attr('action', url);
});
$('#table-masters').DataTable({
    searching: false,
    paging: false,
    info: false
});
</script>
{% endblock scripts %}